language: go

go:
 - master

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - go get -u github.com/golang/lint/golint
  - dep ensure

script:
  - golint -set_exit_status ./...